# Generated by Django 3.2 on 2021-05-19 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('auth_trans_ref_no', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('req_reference_number', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EsewaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('amount', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=50)),
                ('rid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='FonepayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('amount', models.CharField(max_length=100)),
                ('prn', models.CharField(max_length=100)),
                ('bid', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='IMEPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_ref_id_available', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('token', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Is the object deleted?')),
                ('modified_on', models.DateTimeField(blank=True, help_text='Object modified date and time')),
                ('created_on', models.DateTimeField(blank=True, help_text='Object created date and time')),
                ('deleted_on', models.DateTimeField(blank=True, default=None, help_text='Object deleted date and time', null=True)),
                ('payment_status', models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified')], max_length=31)),
                ('status_code', models.CharField(choices=[('CREATED', 'CREATED'), ('MERCHANT_VERIFICATION_FAILED', 'MERCHANT_VERIFICATION_FAILED'), ('NOT_FOUND', 'NOT_FOUND')], default='CREATED', max_length=31)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('USD', 'USD')], default='NPR', max_length=7)),
                ('payment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_assigned', models.BooleanField(blank=True, default=False)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_payments', to='core.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
